// <auto-generated />
using AngularJsDemo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AngularJsDemo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220108084650_InitialData")]
    partial class InitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AngularJsDemo.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MinDays")
                        .HasColumnType("int");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<int>("Transmission")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("AngularJsDemo.Models.Make", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Makes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Lamborghini"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ferrari"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bugatti"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Koenigsegg"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Mercedes"
                        });
                });

            modelBuilder.Entity("AngularJsDemo.Models.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("HorsePower")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2048)");

                    b.Property<int>("MakeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MakeId");

                    b.HasIndex("Name", "MakeId")
                        .IsUnique();

                    b.ToTable("Models");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HorsePower = 450,
                            ImageUrl = "https://ia.tmgrup.com.tr/eccc3c/628/422/0/27/800/564?u=http://i.tmgrup.com.tr/otohaber/2018/02/01/lamborghini-murcielago-hakkinda-bilgi-verir-misiniz-1517491567467.jpg",
                            MakeId = 1,
                            Name = "Murcielago"
                        },
                        new
                        {
                            Id = 2,
                            HorsePower = 500,
                            ImageUrl = "https://arabahaber.com.tr/wp-content/uploads/2018/08/Lamborghini-Aventador-SVJ.jpg",
                            MakeId = 1,
                            Name = "Aventador"
                        },
                        new
                        {
                            Id = 3,
                            HorsePower = 450,
                            ImageUrl = "https://wikiimg.tojsiabtv.com/wikipedia/commons/thumb/d/d3/Lamborghini_Hurac%C3%A1n_LP_610_(17913080973).jpg/1280px-Lamborghini_Hurac%C3%A1n_LP_610_(17913080973).jpg",
                            MakeId = 1,
                            Name = "Hurracan"
                        },
                        new
                        {
                            Id = 4,
                            HorsePower = 450,
                            ImageUrl = "https://www.webtekno.com/images/editor/default/0002/67/62ef54c4fcd5a4b120892e2d58a292a651234db5.jpeg",
                            MakeId = 2,
                            Name = "Enzo"
                        },
                        new
                        {
                            Id = 5,
                            HorsePower = 450,
                            ImageUrl = "https://cdn1.ntv.com.tr/gorsel/Kd6k41vauU2QSAs05QvTuw.jpg?width=960&mode=crop&scale=both",
                            MakeId = 2,
                            Name = "Italia"
                        },
                        new
                        {
                            Id = 6,
                            HorsePower = 450,
                            ImageUrl = "https://staticb.yolcu360.com/blog/wp-content/uploads/2021/04/08212643/Bugatti_Veyron_16-960x483.jpg",
                            MakeId = 3,
                            Name = "Veyron"
                        },
                        new
                        {
                            Id = 7,
                            HorsePower = 450,
                            ImageUrl = "https://ajansotomobil.com/media/news/542.jpg",
                            MakeId = 4,
                            Name = "Agera R"
                        },
                        new
                        {
                            Id = 8,
                            HorsePower = 450,
                            ImageUrl = "https://images.hgmsites.net/hug/koenigsegg-jesko-pre-production-model_100799636_h.jpg",
                            MakeId = 4,
                            Name = "Jesco"
                        },
                        new
                        {
                            Id = 9,
                            HorsePower = 450,
                            ImageUrl = "https://i1.wp.com/www.klasikotom.com/wp-content/uploads/2017/11/mercedes-500sec-amg-27.jpg?ssl=1",
                            MakeId = 5,
                            Name = "500sec"
                        });
                });

            modelBuilder.Entity("AngularJsDemo.Models.Car", b =>
                {
                    b.HasOne("AngularJsDemo.Models.Model", "Model")
                        .WithMany("Cars")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("AngularJsDemo.Models.Model", b =>
                {
                    b.HasOne("AngularJsDemo.Models.Make", "Make")
                        .WithMany("Models")
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Make");
                });

            modelBuilder.Entity("AngularJsDemo.Models.Make", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("AngularJsDemo.Models.Model", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
